vectara:
  corpus_key: feynman
  customer_id: 1169579801
  reindex: false

crawling:
  crawler_type: website

website_crawler:
  urls: ["https://www.feynmanlectures.caltech.edu/"]
  num_per_second: 1
  pos_regex: ["https://www.feynmanlectures.caltech.edu/.*"]
  pages_source: sitemap # options are: (1) 'sitemap' automatically retreived from website (2) 'crawl' for recursive crawling
