vectara:
  corpus_id: 174
  customer_id: 1526022105
  reindex: true

crawling:
  crawler_type: website

website_crawler:
  urls: ["https://gsb.stanford.edu"]
  url_regex: [".*gsb.stanford.edu.*"]
  delay: 0
  pages_source: crawl
  max_depth: 3
  extraction: playwright
