vectara:
  corpus_key: edgar
  : 1526022105
  reindex: true

crawling:
  crawler_type: edgar

edgar_crawler:
  tickers: ['AAPL', 'AMZN', 'GOOG', 'EBAY', 'MSFT', 'INTC', 'NVDA', 'META', 'TSLA', 'AMD', 'CRM', 'NFLX', 'PYPL', 
            'JNJ', 'CSCO', 'JPM', 'NKE', 'WMT', 'V', 'UNH', 'LLY', 'PG', 'HD', 'MRK', 'KO', 'ABBV', 'PEP', 'ORCL',
            'USB', 'WFC', 
           ]
  start_date: "2015-01-01"
  end_date: "2023-05-08"
