vectara:
  corpus_id: 161
  customer_id: 1526022105
  reindex: true

crawling:
  crawler_type: fmp

fmp_crawler:
  tickers:
    [
      "AAPL",
      "ABBV",
      "ABNB",
      "AMD",
      "AMZN",
      "BAC",
      "BBY",
      "C",
      "CRM",
      "CSCO",
      "CVS",
      "CVX",
      "DASH",
      "DIS",
      "EBAY",
      "EXPE",
      "F",
      "GOOG",
      "HD",
      "INTC",
      "JNJ",
      "JPM",
      "KO",
      "LLY",
      "LUV",
      "META",
      "MRK",
      "MSFT",
      "NFLX",
      "NKE",
      "NVDA",
      "ORCL",
      "PEP",
      "PFE",
      "PG",
      "PYPL",
      "RIVN",
      "SLB",
      "SNOW",
      "T",
      "TGT",
      "TSLA",
      "UBER",
      "UNH",
      "USB",
      "V",
      "WFC",
      "WMT",
      "XOM",
    ]

  start_year: 2015
  end_year: 2023
