vectara:
  corpus_key: hn
  reindex: false
  create_corpus: true

crawling:
  crawler_type: hackernews

hackernews_crawler:
  max_articles: 1000
  days_back: 3
  days_back_comprehensive: false
