vectara:
  corpus_key: huggingface-github
  reindex: true

crawling:
  crawler_type: github

github_crawler:
  owner: "huggingface"
  repos:
    [
      "accelerate",
      "datasets",
      "diffusers",
      "optimum",
      "peft",
      "tokenizers",
      "transformers",
    ]
  crawl_code: false
