vectara:
  corpus_key: legalaid-il
  customer_id: 1526022105
  reindex: false

crawling:
  crawler_type: website

website_crawler:
  urls: [https://www.illinoislegalaid.org/]
  pos_regex: [".*illinoislegalaid.*"]
  num_per_second: 1
  pages_source: sitemap # options are: (1) 'sitemap' automatically retreived from website (2) 'crawl' for recursive crawling
