vectara:
  corpus_id: 3
  customer_id: 2081868821
  reindex: true

crawling:
  crawler_type: doc
  document_type: readthedocs

doc_crawler:
  base_urls: ["https://azureml-v2.readthedocs.io/en/stable/quickstart/distributed-training.html"]
  url_regex: [".*azureml-v2.readthedocs.io.*"]
  extensions_to_ignore: ["php", "java", "py", "js"]

