vectara:
  corpus_key: website
  reindex: true

crawling:
  crawler_type: website

website_crawler:
  urls: ["https://vectara.com"]
  num_per_second: 1
  pages_source: sitemap
  pos_regex: [".*"]
  ray_workers: 0
