vectara:
  corpus_id: 141
  customer_id: 1526022105
  reindex: true

crawling:
  crawler_type: website

website_crawler:
  urls: ["https://vectara.com"]
  num_per_second: 1
  pages_source: sitemap
  pos_regex: [".*"]
  extraction: playwright
  ray_workers: 0
