vectara:
  corpus_id: 277
  customer_id: 1526022105
  reindex: true

crawling:
  crawler_type: gdrive

gdrive_crawler:
  delegated_users:
    - 'abhilasha@vectara.com'
    - 'amin@vectara.com'
    - 'aileen@vectara.com'
    - 'sean@vectara.com'
    - 'ali@vectara.com'
    - 'amr@vectara.com'
    - 'irfan@vectara.com'
    - 'forrest@vectara.com'
    - 'miluska@vectara.com'
    - 'aamir@vectara.com'
    - 'nikhil@vectara.com'
    - 'cj@vectara.com'
    - 'shawn@vectara.com'
    - 'shane@vectara.com'
    - 'bahadir@vectara.com'
    - 'deryk@vectara.com'
    - 'adeel@vectara.com'
    - 'ibraheem@vectara.com'
    - 'hareem@vectara.com'
    - 'kyle@vectara.com'
    - 'laurence@vectara.com'
    - 'ryan@vectara.com'
    - 'bader@vectara.com'
    - 'justin@vectara.com'
    - 'utkarsh@vectara.com'
    - 'kayman@vectara.com'
    - 'felicia@vectara.com'
    - 'suleman@vectara.com'
    - 'david@vectara.com'
    - 'miaoran@vectara.com'
    - 'rogger@vectara.com'
    - 'nick@vectara.com'
    - 'kiran@vectara.com'
    - 'ofer@vectara.com'
    - 'alex@vectara.com'
    - 'david.oplatka@vectara.com'
    - 'tony@vectara.com'
    - 'renyi@vectara.com'
    - 'jana@vectara.com'
    - 'danial@vectara.com'
    - 'nagwan@vectara.com'
    - 'tallat@vectara.com'
    - 'vivek@vectara.com'
    - 'parth@vectara.com'
    - 'mansur@vectara.com'
    - 'lancer@vectara.com'
    - 'paul@vectara.com'
    - 'stephanie@vectara.com'
    - 'srinivas@vectara.com'
    - 'hannah@vectara.com'
    - 'nidal@vectara.com'