vectara:
  corpus_key: vectara-docs
  reindex: true
  create_corpus: true

crawling:
  crawler_type: docs

docs_crawler:
  base_urls: ["https://docs.vectara.com/docs"]
  pos_regex: [".*vectara.com/docs.*"]
  neg_regex: [".*vectara.com/docs/rest-api/.*"]
  extensions_to_ignore: [".php", ".java", ".py", ".js"]
  docs_system: docusaurus

