vectara:
  corpus_id: 2
  customer_id: 2081868821
  reindex: true

crawling:
  crawler_type: doc
  document_type: docusaurus

doc_crawler:
  base_urls: ["https://docs.vectara.com/docs"]
  url_regex: [".*vectara.com/docs.*"]
  extensions_to_ignore: ["php", "java", "py", "js"]
