vectara:
  corpus_id: 141
  customer_id: 1526022105
  reindex: true

crawling:
  crawler_type: website

website_crawler:
  urls: ["https://vectara.com"]
  delay: 1
  pages_source: sitemap
  url_regex: [".*"]
  extraction: playwright
