vectara:
  corpus_key: wikipedia
  reindex: True

crawling:
  crawler_type: mediawiki

mediawiki_crawler:
  api_url: "https://en.wikipedia.org/w/api.php"
  n_pages: 1000
  project: "en.wikipedia"
